---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: telegraf-prod
  labels:
    app: telegraf
spec:
  releaseName: telegraf
  chart:
    repository: https://helm.influxdata.com/
    name: telegraf
    version: "1.8.4"
  values:
    envFromSecret: telegraf-influx
    image:
      repo: public.ecr.aws/influxdb/telegraf
      tag: 1.16.2-alpine
    service:
      enabled: false
    config:
      global_tags:
        cluster: itse-apps-prod-1-infra
      agent:
        interval: "300s"
      inputs:
        - x509_cert:
            sources:
              - 'https://activate.mozilla.community:443'
              - 'https://activations.mozilla.com:443'
              - 'https://activations.mozilla.org:443'
              - 'https://addons.mozilla.com:443'
              - 'https://air.cdn.mozilla.net:443'
              - 'https://air.mozilla.com:443'
              - 'https://air.mozilla.org:443'
              - 'https://airmo.mozilla.org:443'
              - 'https://ambassadors.mozilla.org:443'
              - 'https://apps.mozilla.com:443'
              - 'https://apps.mozilla.org:443'
              - 'https://arewefunyet.com:443'
              - 'https://arewestableyet.com:443'
              - 'https://ask.mozilla.org:443'
              - 'https://ateam.planet.mozilla.org:443'
              - 'https://aurora.mozilla.org:443'
              - 'https://beta.mozilla.org:443'
              - 'https://bidiui.mozdev.org:443'
              - 'https://blog.getfirebug.com:443'
              - 'https://blog.getpocket.com:443'
              - 'https://blog.lizardwrangler.com:443'
              - 'https://blog.mozilla.com:443'
              - 'https://blog.mozilla.org:443'
              - 'https://blog.mozillabr.org:443'
              - 'https://blog.mozillaindia.org:443'
              - 'https://blog.mozillaqabd.org:443'
              - 'https://blog.nightly.mozilla.org:443'
              - 'https://blog.seamonkey-project.org:443'
              - 'https://blog.seamonkeyproject.org:443'
              - 'https://blogs.mozilla.com:443'
              - 'https://careers.mozilla.com:443'
              - 'https://ccadb.org:443'
              - 'https://cleopatra.io:443'
              - 'https://college.mozilla.com:443'
              - 'https://college.mozilla.org:443'
              - 'https://communitystore.mozilla.org:443'
              - 'https://confsurvey.mozilla.org:443'
              - 'https://connected.mozilla.org:443'
              - 'https://consultants.mozdev.org:443'
              - 'https://content.mozilla.org:443'
              - 'https://contribute.mozilla.org:443'
              - 'https://contributejson.org:443'
              - 'https://creative.mozilla.org:443'
              - 'https://design.firefox.com:443'
              - 'https://designlanguage.mozilla.org:443'
              - 'https://dev.mozilla.org:443'
              - 'https://dev.sumo.mozit.cloud:443'
              - 'https://devderby.mozilla.org:443'
              - 'https://developer.mozilla.org:443'
              - 'https://dinopark.k8s.dev.sso.allizom.org:443'
              - 'https://dinopark.k8s.test.sso.allizom.org:443'
              - 'https://discourse-dev.itsre-apps.mozit.cloud:443'
              - 'https://discourse-prod.itsre-apps.mozit.cloud:443'
              - 'https://discourse-stage.itsre-apps.mozit.cloud:443'
              - 'https://discourse.mozilla-community.org:443'
              - 'https://discourse.mozilla.org:443'
              - 'https://dnt.mozilla.org:443'
              - 'https://docs.iot.mozilla.org:443'
              - 'https://docs.pub.build.mozilla.org:443'
              - 'https://docs.services.mozilla.com:443'
              - 'https://downloadmozillafirefox.com:443'
              - 'https://dxr.mozilla.org:443'
              - 'https://events.mozilla.org:443'
              - 'https://events.mozspaces.org:443'
              - 'https://experiencethearch.com:443'
              - 'https://experiencethearch.mozilla.org:443'
              - 'https://extensions.mozilla.org:443'
              - 'https://extensiontest.com:443'
              - 'https://fastforgoodcontest.mozilla.org:443'
              - 'https://feedback.mozilla.org:443'
              - 'https://firefox-downloaden.de:443'
              - 'https://firefox.be:443'
              - 'https://firefox.com:443'
              - 'https://firefox.dev:443'
              - 'https://firefox.hu:443'
              - 'https://firefox.pt:443'
              - 'https://firefoxaddons.com:443'
              - 'https://firefoxbrowser.com:443'
              - 'https://firefoxbrowser.org:443'
              - 'https://firefoxflicks.mozilla.org:443'
              - 'https://firefoxquantum.com:443'
              - 'https://firefoxsprint.mozilla.community:443'
              - 'https://forums.mozilla.org:443'
              - 'https://friends.mozilla.org:443'
              - 'https://fsa.mozilla.org:443'
              - 'https://g20openletter.org:443'
              - 'https://games.mozilla.org:443'
              - 'https://geckoview.dev:443'
              - 'https://getfirebug.com:443'
              - 'https://getfirefox.co.uk:443'
              - 'https://getfirefox.com:443'
              - 'https://getfirefox.net:443'
              - 'https://getfirefox.org:443'
              - 'https://git.mozilla.org:443'
              - 'https://guides.mozilla.org:443'
              - 'https://gv.dev:443'
              - 'https://hacks.mozilla.org:443'
              - 'https://hub.mozilla.com:443'
              - 'https://hub.mozilla.org:443'
              - 'https://icons.design.firefox.com:443'
              - 'https://impactmozilla.com:443'
              - 'https://inhumanads.com:443'
              - 'https://input.mozilla.com:443'
              - 'https://input.mozilla.org:443'
              - 'https://interactive-examples.mdn.mozilla.net:443'
              - 'https://internethealthreport.org:443'
              - 'https://interns.mozilla.com:443'
              - 'https://iot.mozilla.org:443'
              - 'https://jira.mozilla.com:443'
              - 'https://jobs.mozilla.com:443'
              - 'https://jobs.mozilla.org:443'
              - 'https://join.mozilla.org:443'
              - 'https://l10n.mozilla.org:443'
              - 'https://l10n.planet.mozilla.org:443'
              - 'https://leadership.mozilla.community:443'
              - 'https://leandatapractices.com:443'
              - 'https://leandatapractices.org:443'
              - 'https://library.mozilla.org:443'
              - 'https://lightning-project.org:443'
              - 'https://lockbox.firefox.com:443'
              - 'https://lockwise.firefox.com:443'
              - 'https://m.input.mozilla.com:443'
              - 'https://maf.mozdev.org:443'
              - 'https://malware-error.mozilla.com:443'
              - 'https://mana.mozilla.org:443'
              - 'https://market.mozilla.org:443'
              - 'https://masterfirefoxos.mozilla.org:443'
              - 'https://mdn.dev:443'
              - 'https://mdn.mozillademos.org:443'
              - 'https://metricsgraphicsjs.org:443'
              - 'https://mobilepartners.mozilla.org:443'
              - 'https://mozdev.org:443'
              - 'https://mozfestea.org:443'
              - 'https://mozilla-podcasts.org:443'
              - 'https://mozilla-uganda.org:443'
              - 'https://mozilla-uk.org:443'
              - 'https://mozilla.com.br:443'
              - 'https://mozilla.com.ru:443'
              - 'https://mozilla.com.tw:443'
              - 'https://mozilla.com:443'
              - 'https://mozilla.design:443'
              - 'https://mozilla.eu:443'
              - 'https://mozilla.fr:443'
              - 'https://mozilla.frl:443'
              - 'https://mozilla.hu:443'
              - 'https://mozilla.it:443'
              - 'https://mozilla.lk:443'
              - 'https://mozilla.lt:443'
              - 'https://mozilla.nl:443'
              - 'https://mozilla.org.uk:443'
              - 'https://mozilla.org:443'
              - 'https://mozilla.ps:443'
              - 'https://mozilla.se:443'
              - 'https://mozillabr.org:443'
              - 'https://mozillaecuador.org:443'
              - 'https://mozillafirefox.com:443'
              - 'https://mozillafirefox.pl:443'
              - 'https://mozillafoundation.com:443'
              - 'https://mozillafoundation.net:443'
              - 'https://mozillapanama.org:443'
              - 'https://mozillaservice.net:443'
              - 'https://mozillausa.org:443'
              - 'https://mozillians.org:443'
              - 'https://mozorg.cdn.mozilla.net:443'
              - 'https://newfirefox.mozilla.community:443'
              - 'https://nightly.mozilla.org:443'
              - 'https://nucleus.mozilla.org:443'
              - 'https://observatory-test.mozilla.org:443'
              - 'https://onemozilla.org:443'
              - 'https://open.mozilla.org:443'
              - 'https://openinnovation.mozilla.org:443'
              - 'https://openwebgames.com:443'
              - 'https://pad.mozilla.org:443'
              - 'https://participation.planet.mozilla.org:443'
              - 'https://paste.mozilla.org:443'
              - 'https://pastebin.mozilla.org:443'
              - 'https://people.mozilla.org:443'
              - 'https://phish-error.mozilla.com:443'
              - 'https://phish-report.mozilla.com:443'
              - 'https://phonebook.mozilla.com:443'
              - 'https://phonebook.mozilla.org:443'
              - 'https://photon.design.firefox.com:443'
              - 'https://planet.bugzilla.org:443'
              - 'https://planet.mozilla.de:443'
              - 'https://planet.mozilla.org:443'
              - 'https://pontoon.mozillalabs.com:443'
              - 'https://popcornjs.org:443'
              - 'https://print.mozilla.com:443'
              - 'https://prod-frankfurt.sumo.mozit.cloud:443'
              - 'https://prod-test.fxa.mozilla-subhub.app:443'
              - 'https://prod.fxa.mozilla-subhub.app:443'
              - 'https://prod.refractr.mozit.cloud:443'
              - 'https://product-identity.design.firefox.com:443'
              - 'https://projects.planet.mozilla.org:443'
              - 'https://prototype.internethealthreport.org:443'
              - 'https://prs.paas.allizom.org:443'
              - 'https://publicsuffix.org:443'
              - 'https://qa.fxa.mozilla-subhub.app:443'
              - 'https://quality.mozilla.org:443'
              - 'https://quickfilters.mozdev.org:443'
              - 'https://quickfolders.mozdev.org:443'
              - 'https://quickpasswords.mozdev.org:443'
              - 'https://refractr.mozilla.org:443'
              - 'https://release.mozilla.org:443'
              - 'https://releng.planet.mozilla.org:443'
              - 'https://removedupes.mozdev.org:443'
              - 'https://reps.mozilla.org:443'
              - 'https://research.mozilla.org:443'
              - 'https://research.planet.mozilla.org:443'
              - 'https://schemas.iot.mozilla.org:443'
              - 'https://securitywiki.mozilla.org:443'
              - 'https://send.firefox.com:443'
              - 'https://sendto.mozilla.org:443'
              - 'https://snippets.cdn.mozilla.net:443'
              - 'https://spark.mozilla.org:443'
              - 'https://srihash.org:443'
              - 'https://sso.mozilla.com:443'
              - 'https://stage-frankfurt.sumo.mozit.cloud:443'
              - 'https://stage.fxa.mozilla-subhub.app:443'
              - 'https://stage.sumo.mozit.cloud:443'
              - 'https://staging.inhumanads.com:443'
              - 'https://start-prod.mozilla.com:443'
              - 'https://start.mozilla.com:443'
              - 'https://start.mozilla.org:443'
              - 'https://static.mozilla.com:443'
              - 'https://store.mozilla.com:443'
              - 'https://store.mozilla.org:443'
              - 'https://students.mozilla.org:443'
              - 'https://support.mozilla.org:443'
              - 'https://supportsprint.mozilla.community:443'
              - 'https://surf.mozilla.org:443'
              - 'https://survey.mozilla.com:443'
              - 'https://sysadmins@mozilla.org:443'
              - 'https://talkback-public.mozilla.org:443'
              - 'https://talkback-reports.mozilla.org:443'
              - 'https://talkback.mozilla.org:443'
              - 'https://taskcluster.net:443'
              - 'https://taskcluster.planet.mozilla.org:443'
              - 'https://techspeakers.mozilla.org:443'
              - 'https://testpilot.firefox.com:443'
              - 'https://theglassroomnyc.org:443'
              - 'https://thehub.mozilla.com:443'
              - 'https://themes.mozilla.org:443'
              - 'https://thunderbird.planet.mozilla.org:443'
              - 'https://tlscanary.mozilla.org:443'
              - 'https://toolkit.mozilla.org:443'
              - 'https://trackertest.org:443'
              - 'https://trackingprotection.info:443'
              - 'https://treestatus.mozilla.org:443'
              - 'https://triagebot.mozilla.org:443'
              - 'https://ux.firefox.com:443'
              - 'https://values.design.firefox.com:443'
              - 'https://videos-cdn.mozilla.net:443'
              - 'https://videos.mozilla.org:443'
              - 'https://voice-sprint.mozilla.community:443'
              - 'https://voice.mozilla.frl:443'
              - 'https://voice.mozilla.org:443'
              - 'https://webdev.mozilla.org:443'
              - 'https://webmaster@mozilla.com:443'
              - 'https://website-archive.mozilla.org:443'
              - 'https://website-beta.mozilla.org:443'
              - 'https://webwewant.mozilla.org:443'
              - 'https://whatsdeployed.paas.allizom.org:443'
              - 'https://wiki.mozilla.com:443'
              - 'https://wiki.mozilla.org:443'
              - 'https://wot.iot.mozilla.org:443'
              - 'https://www-archive.mozilla.org:443'
              - 'https://www.arewefunyet.com:443'
              - 'https://www.bugzilla.org:443'
              - 'https://www.ccadb.org:443'
              - 'https://www.firefox.be:443'
              - 'https://www.firefox.com:443'
              - 'https://www.firefox.hu:443'
              - 'https://www.firefox.lt:443'
              - 'https://www.firefox.pt:443'
              - 'https://www.firefoxbrowser.com:443'
              - 'https://www.firefoxbrowser.org:443'
              - 'https://www.getfirefox.com:443'
              - 'https://www.getfirefox.de:443'
              - 'https://www.getfirefox.net:443'
              - 'https://www.getfirefox.org:443'
              - 'https://www.impactmozilla.com:443'
              - 'https://www.inhumanads.com:443'
              - 'https://www.internethealthreport.org:443'
              - 'https://www.itisatrap.org:443'
              - 'https://www.leandatapractices.com:443'
              - 'https://www.leandatapractices.org:443'
              - 'https://www.lightning-project.org:443'
              - 'https://www.mozdev.org:443'
              - 'https://www.mozilla.at:443'
              - 'https://www.mozilla.ca:443'
              - 'https://www.mozilla.com.ru:443'
              - 'https://www.mozilla.com:443'
              - 'https://www.mozilla.eu:443'
              - 'https://www.mozilla.fr:443'
              - 'https://www.mozilla.frl:443'
              - 'https://www.mozilla.hu:443'
              - 'https://www.mozilla.net:443'
              - 'https://www.mozilla.nl:443'
              - 'https://www.mozilla.org.uk:443'
              - 'https://www.mozillabr.org:443'
              - 'https://www.mozillaecuador.org:443'
              - 'https://www.mozillafirefox.com:443'
              - 'https://www.mozillafirefox.pl:443'
              - 'https://www.mozillaservice.net:443'
              - 'https://www.onemozilla.org:443'
              - 'https://www.popcornjs.org:443'
              - 'https://www.publicsuffix.org:443'
              - 'https://www.smartdogz.org:443'
              - 'https://www.srihash.org:443'
              - 'https://www.store.mozilla.org:443'
              - 'https://www.support.mozilla.org:443'
              - 'https://www.theglassroomnyc.org:443'
              - 'https://www.trackingprotection.info:443'
              - 'https://www.update-firefox.com:443'
              - 'https://www.webfwd.net:443'
              - 'https://www.webfwd.org:443'
              - 'https://wwww.mozilla.it:443'
              - 'https://zombiekeys.mozdev.org:443'
 
      outputs:
        - influxdb:
            skip_database_creation: true
            urls: ["${INFLUX_URL}"]
            database: "${INFLUX_DB}"
            timeout: "15s"
            username: "${INFLUX_USER}"
            password: "${INFLUX_PW}"
