---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etherpad
  namespace: etherpad-prod
  labels:
    app: etherpad
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(v[0-9]+.[0-9]+.[0-9]+)$
spec:
  releaseName: etherpad
  chart:
    repository: https://mozilla-it.github.io/helm-charts/
    name: etherpad
    version: "1.0.0"
  values:
    configMap:
      data: {}
    externalSecrets:
      enabled: true
      secrets:
      - key: /prod/etherpad/envvar
        name: ADMIN_PASSWORD
        property: ADMIN_PASSWORD
      - key: /prod/etherpad/envvar
        name: DB_HOST
        property: DB_HOST
      - key: /prod/etherpad/envvar
        name: DB_NAME
        property: DB_NAME
      - key: /prod/etherpad/envvar
        name: DB_PASS
        property: DB_PASS
      - key: /prod/etherpad/envvar
        name: DB_USER
        property: DB_USER
      - key: /prod/etherpad/envvar
        name: ETHERPAD_API_KEY
        property: ETHERPAD_API_KEY
      - key: /prod/etherpad/envvar
        name: ETHERPAD_SESSION_KEY
        property: ETHERPAD_SESSION_KEY
    image:
      pullPolicy: Always
      repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/etherpad
      tag: v1.0.0
    ingress:
      hosts:
      - host: pad.mozilla.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: oidc-gateway
          servicePort: 80
      - host: pad.prod.mozit.cloud
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: oidc-gateway
          servicePort: 80
      le:
        issuer_create: true
        name: prod
      tls:
      - hosts:
        - pad.mozilla.org
        secretName: chart-pad-mozilla-org
      - hosts:
        - pad.prod.mozit.cloud
        secretName: chart-pad-prod-mozit-cloud
